import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `payload generate:types` — not hand-written source.
    "payload-types.ts",
    // Scaffolded by Payload (`(payload)` route group + importMap) and
    // regenerated on demand; not hand-written source.
    "src/app/(payload)/**",
    // One-off local dev/debug scripts, not part of the app build.
    "*.cjs",
    "scripts-local/**",
  ]),
  {
    // Standalone Node scripts and the BullMQ worker: no React, and `console` is
    // their only output channel.
    files: ["src/scripts/**/*.ts", "src/worker/**/*.ts", "src/payload/seed/**/*.ts"],
    rules: {
      "@typescript-eslint/no-explicit-any": "warn",
    },
  },
]);

export default eslintConfig;
