/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    'audit-logs': AuditLog;
    'paper-types': PaperType;
    'print-sizes': PrintSize;
    'finishing-options': FinishingOption;
    'print-methods': PrintMethod;
    'product-types': ProductType;
    'price-lists': PriceList;
    'turnaround-options': TurnaroundOption;
    'preflight-rules': PreflightRule;
    'public-assets': PublicAsset;
    artworks: Artwork;
    orders: Order;
    'order-items': OrderItem;
    proofs: Proof;
    quotes: Quote;
    payments: Payment;
    invoices: Invoice;
    'design-packages': DesignPackage;
    'design-projects': DesignProject;
    briefs: Brief;
    organizations: Organization;
    'credit-transactions': CreditTransaction;
    'portfolio-items': PortfolioItem;
    posts: Post;
    pages: Page;
    faqs: Faq;
    templates: Template;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    'paper-types': PaperTypesSelect<false> | PaperTypesSelect<true>;
    'print-sizes': PrintSizesSelect<false> | PrintSizesSelect<true>;
    'finishing-options': FinishingOptionsSelect<false> | FinishingOptionsSelect<true>;
    'print-methods': PrintMethodsSelect<false> | PrintMethodsSelect<true>;
    'product-types': ProductTypesSelect<false> | ProductTypesSelect<true>;
    'price-lists': PriceListsSelect<false> | PriceListsSelect<true>;
    'turnaround-options': TurnaroundOptionsSelect<false> | TurnaroundOptionsSelect<true>;
    'preflight-rules': PreflightRulesSelect<false> | PreflightRulesSelect<true>;
    'public-assets': PublicAssetsSelect<false> | PublicAssetsSelect<true>;
    artworks: ArtworksSelect<false> | ArtworksSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'order-items': OrderItemsSelect<false> | OrderItemsSelect<true>;
    proofs: ProofsSelect<false> | ProofsSelect<true>;
    quotes: QuotesSelect<false> | QuotesSelect<true>;
    payments: PaymentsSelect<false> | PaymentsSelect<true>;
    invoices: InvoicesSelect<false> | InvoicesSelect<true>;
    'design-packages': DesignPackagesSelect<false> | DesignPackagesSelect<true>;
    'design-projects': DesignProjectsSelect<false> | DesignProjectsSelect<true>;
    briefs: BriefsSelect<false> | BriefsSelect<true>;
    organizations: OrganizationsSelect<false> | OrganizationsSelect<true>;
    'credit-transactions': CreditTransactionsSelect<false> | CreditTransactionsSelect<true>;
    'portfolio-items': PortfolioItemsSelect<false> | PortfolioItemsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    templates: TemplatesSelect<false> | TemplatesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'operator' | 'designer' | 'customer' | 'b2b';
  fullName?: string | null;
  phone?: string | null;
  organization?: (number | null) | Organization;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations".
 */
export interface Organization {
  id: number;
  name: string;
  taxId?: string | null;
  creditLimit?: number | null;
  balance?: number | null;
  baseDiscount?: number | null;
  users?: (number | User)[] | null;
  status?: ('active' | 'suspended') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: number;
  actor?: (number | null) | User;
  action: string;
  entity: string;
  entityId: string;
  diff?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  ip?: string | null;
  userAgent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "paper-types".
 */
export interface PaperType {
  id: number;
  name: string;
  category: 'تحریر' | 'گلاسه' | 'کتان' | 'کاربن‌لس' | 'مقوا' | 'PVC' | 'بنر';
  allowedGrammages?:
    | {
        grammage: number;
        id?: string | null;
      }[]
    | null;
  color?: string | null;
  description?: string | null;
  textureImage?: (number | null) | PublicAsset;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "public-assets".
 */
export interface PublicAsset {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "print-sizes".
 */
export interface PrintSize {
  id: number;
  name: string;
  category?: string | null;
  finalWidth: number;
  finalHeight: number;
  defaultBleed: number;
  safeMargin: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "finishing-options".
 */
export interface FinishingOption {
  id: number;
  name: string;
  code: string;
  calculationType: 'perForm' | 'perUnit' | 'perSquareMeter' | 'flat';
  minCost?: number | null;
  requiresDieLayer?: boolean | null;
  description?: string | null;
  exampleImage?: (number | null) | PublicAsset;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "print-methods".
 */
export interface PrintMethod {
  id: number;
  name: string;
  method: 'digital' | 'offset' | 'largeFormat';
  minQuantity?: number | null;
  maxQuantity?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-types".
 */
export interface ProductType {
  id: number;
  name: string;
  slug: string;
  printMethod: number | PrintMethod;
  allowedSizes?: (number | PrintSize)[] | null;
  allowedPapers?: (number | PaperType)[] | null;
  allowedFinishings?: (number | FinishingOption)[] | null;
  pricingModel: 'tier' | 'area' | 'perSheet' | 'rfq';
  minQuantity?: number | null;
  quantityTiers?:
    | {
        quantity: number;
        id?: string | null;
      }[]
    | null;
  allowDoubleSided?: boolean | null;
  standardProductionDays: number;
  seoContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  images?: (number | PublicAsset)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "price-lists".
 */
export interface PriceList {
  id: number;
  version: string;
  status: 'draft' | 'active' | 'archived';
  validFrom: string;
  rows?:
    | {
        productType?: (number | null) | ProductType;
        paperType?: (number | null) | PaperType;
        finishingOption?: (number | null) | FinishingOption;
        grammage?: number | null;
        sides?: number | null;
        basePrice: number;
        id?: string | null;
      }[]
    | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "turnaround-options".
 */
export interface TurnaroundOption {
  id: number;
  name: string;
  daysToAdd: number;
  priceMultiplier: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "preflight-rules".
 */
export interface PreflightRule {
  id: number;
  name: string;
  productType: number | ProductType;
  dimensions: {
    widthMm: number;
    heightMm: number;
    bleedMm: number;
    toleranceMm: number;
  };
  quality?: {
    minResolutionDpi?: number | null;
    allowRgb?: boolean | null;
    requirePdfX?: boolean | null;
  };
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "artworks".
 */
export interface Artwork {
  id: number;
  owner: number | User;
  originalName: string;
  fileHash?: string | null;
  virusScanStatus?: ('pending' | 'clean' | 'infected') | null;
  preflightResult?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  previewPath?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  orderNumber: string;
  customer: number | User;
  status:
    | 'draft'
    | 'awaiting_payment'
    | 'paid'
    | 'file_review'
    | 'needs_customer_action'
    | 'awaiting_proof'
    | 'proof_approved'
    | 'prepress'
    | 'printing'
    | 'finishing'
    | 'quality_check'
    | 'ready'
    | 'shipped'
    | 'delivered'
    | 'closed'
    | 'on_hold'
    | 'cancelled'
    | 'refunded';
  items?: (number | OrderItem)[] | null;
  totals: {
    subtotal: number;
    discount: number;
    vat: number;
    shipping: number;
    total: number;
  };
  priceSnapshot?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  priceListVersion?: string | null;
  shippingAddress?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  shippingMethod?: string | null;
  shippingProvider?: string | null;
  trackingCode?: string | null;
  trackingUrl?: string | null;
  internalNotes?: string | null;
  customerNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order-items".
 */
export interface OrderItem {
  id: number;
  productType: number | ProductType;
  configuration:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  quantity: number;
  unitPrice: number;
  totalPrice: number;
  artwork?: (number | null) | Artwork;
  designProject?: (number | null) | DesignProject;
  proofs?: (number | Proof)[] | null;
  itemStatus?:
    | ('pending' | 'prepress' | 'printing' | 'finishing' | 'quality_check' | 'ready' | 'done' | 'on_hold' | 'cancelled')
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "design-projects".
 */
export interface DesignProject {
  id: number;
  customer: number | User;
  designer?: (number | null) | User;
  package: number | DesignPackage;
  orderItem?: (number | null) | OrderItem;
  brief?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  rounds?:
    | {
        files?: (number | Artwork)[] | null;
        feedback?: string | null;
        id?: string | null;
      }[]
    | null;
  deliverables?: (number | Artwork)[] | null;
  status?: ('brief_submitted' | 'in_design' | 'awaiting_feedback' | 'revision' | 'final_approval' | 'delivered') | null;
  finalApprovalSignature?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "design-packages".
 */
export interface DesignPackage {
  id: number;
  name: string;
  price: number;
  revisions: number;
  deliveryTime: number;
  deliverables?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proofs".
 */
export interface Proof {
  id: number;
  orderItem: number | OrderItem;
  customer: number | User;
  version: number;
  status?: ('pending' | 'approved' | 'rejected') | null;
  customerFeedback?: string | null;
  approvalDate?: string | null;
  approvalIp?: string | null;
  signedAgreementText?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotes".
 */
export interface Quote {
  id: number;
  customer?: (number | null) | User;
  contactInfo?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  requestDetails: string;
  attachments?: (number | Artwork)[] | null;
  proposedPrice?: number | null;
  adminNotes?: string | null;
  expiryDate?: string | null;
  status?: ('pending' | 'answered' | 'converted' | 'expired') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments".
 */
export interface Payment {
  id: number;
  order: number | Order;
  customer: number | User;
  amount: number;
  provider: string;
  refId?: string | null;
  status?: ('pending' | 'success' | 'failed' | 'refunded') | null;
  idempotencyKey: string;
  rawPayload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoices".
 */
export interface Invoice {
  id: number;
  order: number | Order;
  customer: number | User;
  serialNumber: string;
  vatAmount: number;
  buyerInfo:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  pdfPath?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "briefs".
 */
export interface Brief {
  id: number;
  customer: number | User;
  projectType: string;
  answers:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "credit-transactions".
 */
export interface CreditTransaction {
  id: number;
  organization: number | Organization;
  amount: number;
  type: 'charge' | 'deduct';
  orderReference?: (number | null) | Order;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio-items".
 */
export interface PortfolioItem {
  id: number;
  title: string;
  images: (number | PublicAsset)[];
  customer?: string | null;
  category?: string | null;
  printSpecs?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  author?: (number | null) | User;
  publishedDate?: string | null;
  coverImage?: (number | null) | PublicAsset;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  category?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "templates".
 */
export interface Template {
  id: number;
  name: string;
  slug: string;
  category: 'کارت ویزیت' | 'تراکت' | 'سربرگ' | 'فاکتور' | 'پاکت';
  productType?: (number | null) | ProductType;
  description?: string | null;
  previewImage: number | PublicAsset;
  downloadFile: number | PublicAsset;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: number | AuditLog;
      } | null)
    | ({
        relationTo: 'paper-types';
        value: number | PaperType;
      } | null)
    | ({
        relationTo: 'print-sizes';
        value: number | PrintSize;
      } | null)
    | ({
        relationTo: 'finishing-options';
        value: number | FinishingOption;
      } | null)
    | ({
        relationTo: 'print-methods';
        value: number | PrintMethod;
      } | null)
    | ({
        relationTo: 'product-types';
        value: number | ProductType;
      } | null)
    | ({
        relationTo: 'price-lists';
        value: number | PriceList;
      } | null)
    | ({
        relationTo: 'turnaround-options';
        value: number | TurnaroundOption;
      } | null)
    | ({
        relationTo: 'preflight-rules';
        value: number | PreflightRule;
      } | null)
    | ({
        relationTo: 'public-assets';
        value: number | PublicAsset;
      } | null)
    | ({
        relationTo: 'artworks';
        value: number | Artwork;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'order-items';
        value: number | OrderItem;
      } | null)
    | ({
        relationTo: 'proofs';
        value: number | Proof;
      } | null)
    | ({
        relationTo: 'quotes';
        value: number | Quote;
      } | null)
    | ({
        relationTo: 'payments';
        value: number | Payment;
      } | null)
    | ({
        relationTo: 'invoices';
        value: number | Invoice;
      } | null)
    | ({
        relationTo: 'design-packages';
        value: number | DesignPackage;
      } | null)
    | ({
        relationTo: 'design-projects';
        value: number | DesignProject;
      } | null)
    | ({
        relationTo: 'briefs';
        value: number | Brief;
      } | null)
    | ({
        relationTo: 'organizations';
        value: number | Organization;
      } | null)
    | ({
        relationTo: 'credit-transactions';
        value: number | CreditTransaction;
      } | null)
    | ({
        relationTo: 'portfolio-items';
        value: number | PortfolioItem;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'templates';
        value: number | Template;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  fullName?: T;
  phone?: T;
  organization?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  actor?: T;
  action?: T;
  entity?: T;
  entityId?: T;
  diff?: T;
  ip?: T;
  userAgent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "paper-types_select".
 */
export interface PaperTypesSelect<T extends boolean = true> {
  name?: T;
  category?: T;
  allowedGrammages?:
    | T
    | {
        grammage?: T;
        id?: T;
      };
  color?: T;
  description?: T;
  textureImage?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "print-sizes_select".
 */
export interface PrintSizesSelect<T extends boolean = true> {
  name?: T;
  category?: T;
  finalWidth?: T;
  finalHeight?: T;
  defaultBleed?: T;
  safeMargin?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "finishing-options_select".
 */
export interface FinishingOptionsSelect<T extends boolean = true> {
  name?: T;
  code?: T;
  calculationType?: T;
  minCost?: T;
  requiresDieLayer?: T;
  description?: T;
  exampleImage?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "print-methods_select".
 */
export interface PrintMethodsSelect<T extends boolean = true> {
  name?: T;
  method?: T;
  minQuantity?: T;
  maxQuantity?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-types_select".
 */
export interface ProductTypesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  printMethod?: T;
  allowedSizes?: T;
  allowedPapers?: T;
  allowedFinishings?: T;
  pricingModel?: T;
  minQuantity?: T;
  quantityTiers?:
    | T
    | {
        quantity?: T;
        id?: T;
      };
  allowDoubleSided?: T;
  standardProductionDays?: T;
  seoContent?: T;
  images?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "price-lists_select".
 */
export interface PriceListsSelect<T extends boolean = true> {
  version?: T;
  status?: T;
  validFrom?: T;
  rows?:
    | T
    | {
        productType?: T;
        paperType?: T;
        finishingOption?: T;
        grammage?: T;
        sides?: T;
        basePrice?: T;
        id?: T;
      };
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "turnaround-options_select".
 */
export interface TurnaroundOptionsSelect<T extends boolean = true> {
  name?: T;
  daysToAdd?: T;
  priceMultiplier?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "preflight-rules_select".
 */
export interface PreflightRulesSelect<T extends boolean = true> {
  name?: T;
  productType?: T;
  dimensions?:
    | T
    | {
        widthMm?: T;
        heightMm?: T;
        bleedMm?: T;
        toleranceMm?: T;
      };
  quality?:
    | T
    | {
        minResolutionDpi?: T;
        allowRgb?: T;
        requirePdfX?: T;
      };
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "public-assets_select".
 */
export interface PublicAssetsSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "artworks_select".
 */
export interface ArtworksSelect<T extends boolean = true> {
  owner?: T;
  originalName?: T;
  fileHash?: T;
  virusScanStatus?: T;
  preflightResult?: T;
  previewPath?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  customer?: T;
  status?: T;
  items?: T;
  totals?:
    | T
    | {
        subtotal?: T;
        discount?: T;
        vat?: T;
        shipping?: T;
        total?: T;
      };
  priceSnapshot?: T;
  priceListVersion?: T;
  shippingAddress?: T;
  shippingMethod?: T;
  shippingProvider?: T;
  trackingCode?: T;
  trackingUrl?: T;
  internalNotes?: T;
  customerNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order-items_select".
 */
export interface OrderItemsSelect<T extends boolean = true> {
  productType?: T;
  configuration?: T;
  quantity?: T;
  unitPrice?: T;
  totalPrice?: T;
  artwork?: T;
  designProject?: T;
  proofs?: T;
  itemStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proofs_select".
 */
export interface ProofsSelect<T extends boolean = true> {
  orderItem?: T;
  customer?: T;
  version?: T;
  status?: T;
  customerFeedback?: T;
  approvalDate?: T;
  approvalIp?: T;
  signedAgreementText?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotes_select".
 */
export interface QuotesSelect<T extends boolean = true> {
  customer?: T;
  contactInfo?: T;
  requestDetails?: T;
  attachments?: T;
  proposedPrice?: T;
  adminNotes?: T;
  expiryDate?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments_select".
 */
export interface PaymentsSelect<T extends boolean = true> {
  order?: T;
  customer?: T;
  amount?: T;
  provider?: T;
  refId?: T;
  status?: T;
  idempotencyKey?: T;
  rawPayload?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoices_select".
 */
export interface InvoicesSelect<T extends boolean = true> {
  order?: T;
  customer?: T;
  serialNumber?: T;
  vatAmount?: T;
  buyerInfo?: T;
  pdfPath?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "design-packages_select".
 */
export interface DesignPackagesSelect<T extends boolean = true> {
  name?: T;
  price?: T;
  revisions?: T;
  deliveryTime?: T;
  deliverables?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "design-projects_select".
 */
export interface DesignProjectsSelect<T extends boolean = true> {
  customer?: T;
  designer?: T;
  package?: T;
  orderItem?: T;
  brief?: T;
  rounds?:
    | T
    | {
        files?: T;
        feedback?: T;
        id?: T;
      };
  deliverables?: T;
  status?: T;
  finalApprovalSignature?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "briefs_select".
 */
export interface BriefsSelect<T extends boolean = true> {
  customer?: T;
  projectType?: T;
  answers?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations_select".
 */
export interface OrganizationsSelect<T extends boolean = true> {
  name?: T;
  taxId?: T;
  creditLimit?: T;
  balance?: T;
  baseDiscount?: T;
  users?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "credit-transactions_select".
 */
export interface CreditTransactionsSelect<T extends boolean = true> {
  organization?: T;
  amount?: T;
  type?: T;
  orderReference?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio-items_select".
 */
export interface PortfolioItemsSelect<T extends boolean = true> {
  title?: T;
  images?: T;
  customer?: T;
  category?: T;
  printSpecs?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  author?: T;
  publishedDate?: T;
  coverImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  metaTitle?: T;
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "templates_select".
 */
export interface TemplatesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  category?: T;
  productType?: T;
  description?: T;
  previewImage?: T;
  downloadFile?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName?: string | null;
  contactEmail?: string | null;
  contactPhone?: string | null;
  address?: string | null;
  socialLinks?:
    | {
        platform?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  contactEmail?: T;
  contactPhone?: T;
  address?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}